# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel-Challenge-2023-Rui.Sousa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel-Challenge-2023-Rui.Sousa
  pod 'SDWebImage'

end
